#line 3 "asm-lexer.lpp"
#include "asm-parser.h"
#include <cstdlib>

using namespace std;



#line 10 "asm-lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[248] =
    {   0,
        0,    0,    0,    0,    0,    0,   63,   50,   48,   46,
       45,   50,   50,   50,   50,   49,   50,   50,   50,   50,
       50,   50,   50,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   60,   62,   61,   62,   53,   51,
       53,   48,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   44,    0,   47,
        0,   46,   13,   16,   43,   43,   43,   43,   43,   43,
       43,   43,    3,   43,   43,   43,   43,   43,   43,   43,

       43,    3,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,    0,
       60,   59,   57,   58,   54,   56,   55,   52,    2,    2,
        1,   21,   20,   18,   17,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
       14,   15,   15,   15,   15,   15,   15,   15,   15,   47,
       16,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,    3,   43,   43,   43,    3,   43,   43,    2,
       27,   29,   26,   28,   19,   34,   33,   31,   30,    0,
       23,   22,    0,    0,   25,   24,    0,    0,   15,   12,

       15,   15,    4,   15,   15,   15,   15,   43,   43,   43,
       43,   43,   43,   43,    3,   43,   43,   43,   43,   40,
       42,   39,   41,   32,   36,   35,   38,   37,    7,   15,
       15,   15,    5,    6,   15,   43,   43,   15,   15,    9,
       15,   15,   10,    8,   15,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       16,   16,   16,   16,   16,   16,   15,   18,   19,    1,
        1,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   44,   46,
        1,   47,    1,    1,    1,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   44,   44,   57,   44,   58,
       59,   44,   44,   60,   61,   62,   63,   44,   44,   44,
       44,   44,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    5,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    3,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[261] =
    {   0,
        0,    0,   61,   63,   65,   66,  437,  438,  434,  438,
      438,   55,   51,   55,   72,  438,   74,   46,  426,   67,
      431,   70,    0,   76,   76,  397,   62,  394,    0,  405,
      408,   82,   78,   79,   88,   90,  390,   85,  386,   97,
       87,  107,  391,  419,    0,  438,  438,   86,  438,  438,
      411,  422,  134,  139,  124,  141,   99,  383,  143,  145,
      126,  382,  142,  144,  414,  145,  146,  413,  401,  115,
      151,  127,  153,  154,  155,  156,  157,  438,  161,    0,
      415,  438,  438,    0,    0,  392,  391,  389,  372,  379,
      388,  368,    0,  369,  376,  160,  384,  370,  367,  376,

      362,  360,  369,  363,  359,  362,  139,  362,  159,  368,
      370,  373,  371,  362,  361,  360,  359,  358,  349,  165,
        0,  438,  438,  438,  438,  438,  438,  438,  181,  186,
      200,  208,  211,  438,  438,  350,  378,  377,  376,  375,
      345,  172,  208,  210,  212,  214,  216,  218,  220,  363,
      438,  174,  188,  193,  181,  220,  223,  224,  225,    0,
        0,  339,  338,  341,  338,  335,  337,  218,  219,  221,
      335,  332,  350,  342,  329,  333,  342,  341,  341,  233,
      438,  438,  438,  438,  438,  246,  247,  438,  438,  354,
      438,  438,  340,  339,  438,  438,  336,  327,  228,  311,

      242,  235,  296,  243,   71,  244,  246,  296,  281,  273,
      272,  269,  268,  260,  275,  260,  249,  256,  258,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  271,  245,
      247,  248,  269,  268,  250,  252,  239,  253,  249,  261,
      256,  252,  260,  259,  257,  258,  438,  315,  321,  327,
      263,  330,  336,   70,  339,  345,  351,  354,  357,  360
    } ;

static yyconst flex_int16_t yy_def[261] =
    {   0,
      247,    1,  248,  248,  249,  249,  247,  247,  247,  247,
      247,  250,  247,  247,  247,  247,  247,  251,  247,  252,
      253,  247,  254,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  256,  247,  247,  257,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  247,  252,  259,
      253,  247,  247,  260,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  247,
      256,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  258,
      247,  258,  258,  258,  258,  258,  258,  258,  258,  259,
      260,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  258,  258,
      258,  258,  258,  258,  258,  255,  255,  258,  258,  258,
      258,  258,  258,  258,  258,  258,    0,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247
    } ;

static yyconst flex_int16_t yy_nxt[502] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,    8,   15,
       16,   17,   18,   19,   20,   20,   20,    8,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   29,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   29,   29,   29,   43,   29,    8,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   44,
       29,   29,   29,   46,   47,   46,   47,   50,   50,   54,
       54,   54,   55,   51,   51,   84,   59,   63,   64,   66,
       67,   79,   79,   79,   83,   83,   83,   91,  151,   56,
       57,   92,   58,   60,   61,   70,   62,   71,   72,   73,

       86,   74,   75,   88,   93,   76,   77,   48,   96,   48,
       87,   98,   89,   93,   93,  104,   97,   99,  100,  111,
      106,  101,  109,  102,  233,  105,  107,  112,  113,  103,
      114,   65,  151,   68,  123,  134,  110,  135,  124,  132,
      132,  115,  116,  125,  151,  126,  117,  127,  129,  129,
      129,  130,  118,  131,  131,  131,  133,  133,  137,  137,
      138,  138,  139,  142,  140,  144,  146,  148,  151,  152,
      151,  151,  151,  151,  151,   79,   79,   79,  174,   93,
      143,  176,  145,  147,  149,  167,   59,  191,  191,  154,
       93,  151,  168,  169,  170,  129,  129,  129,  151,  177,

      180,  180,  180,   60,   61,  151,   62,  158,  153,  155,
      151,  156,  130,  157,  131,  131,  131,  181,  159,  182,
      183,  199,  184,  192,  192,  193,  193,  194,  194,  195,
      195,  196,  196,  197,  197,  198,  198,  151,  200,  202,
      151,  151,  151,  210,  212,  151,  214,  180,  180,  180,
      201,   93,  151,  211,  213,  220,  222,  221,  223,  151,
      151,  151,  151,  151,  151,  151,  151,  151,   69,  151,
      151,  206,  204,  151,  151,  151,  151,  151,  151,   93,
      205,  203,   93,  231,  207,  151,  151,  229,  151,   93,
      232,  230,   93,   93,  239,  237,   93,  236,   93,   93,

      234,  235,   93,   93,  240,  243,  238,  241,  242,  244,
      245,   93,   93,  151,  246,   45,   45,   45,   45,   45,
       45,   49,   49,   49,   49,   49,   49,   53,  151,   53,
       53,   53,   53,   80,  228,   80,   81,   81,   81,   81,
       81,   81,   85,  227,   85,  121,  226,  225,  121,  121,
      121,  122,  122,  122,  122,  122,  122,  150,  150,  150,
      160,  224,  160,  161,  219,  161,  218,  217,  216,   93,
      215,   93,   93,   93,  209,   93,   93,  208,   93,   93,
      151,  190,  189,  188,  187,  186,  185,   93,   93,   93,
       93,   93,   93,   93,  179,  178,   93,  175,  173,   93,

       93,  172,   93,   93,   93,   93,   93,  171,  166,   93,
       93,  165,  164,  163,  162,   93,   93,   82,  151,   67,
       64,  141,  136,   52,  128,  120,  119,  108,   93,   95,
       94,   93,   90,   82,   78,   52,  247,    7,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247
    } ;

static yyconst flex_int16_t yy_chk[502] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    5,    6,   12,
       12,   12,   13,    5,    6,  254,   14,   15,   15,   17,
       17,   20,   20,   20,   22,   22,   22,   27,  205,   13,
       13,   27,   13,   14,   14,   18,   14,   18,   18,   18,

       24,   18,   18,   25,   34,   18,   18,    3,   32,    4,
       24,   33,   25,   35,   34,   36,   32,   33,   34,   41,
       38,   35,   40,   35,  205,   36,   38,   41,   41,   35,
       42,   15,   70,   17,   48,   57,   40,   57,   48,   55,
       55,   42,   42,   48,   72,   48,   42,   48,   53,   53,
       53,   54,   42,   54,   54,   54,   56,   56,   59,   59,
       60,   60,   61,   63,   61,   64,   66,   67,   71,   70,
       73,   74,   75,   76,   77,   79,   79,   79,  107,  107,
       63,  109,   64,   66,   67,   96,  120,  142,  142,   72,
       96,  152,   96,   96,   96,  129,  129,  129,  155,  109,

      130,  130,  130,  120,  120,  153,  120,   76,   71,   73,
      154,   74,  131,   75,  131,  131,  131,  132,   77,  132,
      133,  152,  133,  143,  143,  144,  144,  145,  145,  146,
      146,  147,  147,  148,  148,  149,  149,  156,  153,  155,
      157,  158,  159,  168,  169,  199,  170,  180,  180,  180,
      154,  170,  202,  168,  169,  186,  187,  186,  187,  201,
      204,  206,  230,  207,  231,  232,  239,  235,  251,  242,
      238,  158,  157,  241,  245,  246,  244,  243,  240,  237,
      157,  156,  236,  202,  159,  234,  233,  199,  229,  219,
      204,  201,  218,  217,  231,  216,  215,  214,  213,  212,

      206,  207,  211,  210,  232,  239,  230,  235,  238,  241,
      242,  209,  208,  203,  245,  248,  248,  248,  248,  248,
      248,  249,  249,  249,  249,  249,  249,  250,  200,  250,
      250,  250,  250,  252,  198,  252,  253,  253,  253,  253,
      253,  253,  255,  197,  255,  256,  194,  193,  256,  256,
      256,  257,  257,  257,  257,  257,  257,  258,  258,  258,
      259,  190,  259,  260,  179,  260,  178,  177,  176,  175,
      174,  173,  172,  171,  167,  166,  165,  164,  163,  162,
      150,  141,  140,  139,  138,  137,  136,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  108,  106,  105,

      104,  103,  102,  101,  100,   99,   98,   97,   95,   94,
       92,   91,   90,   89,   88,   87,   86,   81,   69,   68,
       65,   62,   58,   52,   51,   44,   43,   39,   37,   31,
       30,   28,   26,   21,   19,    9,    7,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "asm-lexer.lpp"
/**/



#line 35 "asm-lexer.lpp"

#define MAX_STR_CONST 256

char string_buf[MAX_STR_CONST];
char *string_buf_ptr;

int getRegNum(const char * str);
void createRegArg(asm_arg *& arg, YYLTYPE *& loc, const char * str,
              const TypeOfArgument& type, const int& offset, const bool rel);
void createConstIntArg(asm_arg *& arg, YYLTYPE *& loc, const int _val);
void createConstRealArg(asm_arg *& arg, YYLTYPE *& loc, const float _val);
void createSpecialRegArg(asm_arg *& arg, YYLTYPE *& loc,
              const enum Registers& reg);
void createSpecialAddrRegArg(asm_arg *& arg, YYLTYPE *& loc,
              const enum Registers& reg, const bool rel);

#define YY_USER_ACTION							\
   do {									\
      yylloc->first_column = yylloc->last_column;			\
      yylloc->last_column += yyleng;					\
   } while(0);

#line 682 "asm-lexer.cpp"

#define INITIAL 0
#define STRING_CONTEXT 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

YYSTYPE * yyget_lval (void );

void yyset_lval (YYSTYPE * yylval_param  );

       YYLTYPE *yyget_lloc (void );
    
        void yyset_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 59 "asm-lexer.lpp"


#line 883 "asm-lexer.cpp"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 438 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "asm-lexer.lpp"
{
            yylval->integer = atoi(yytext+1);
            return INTEGER;
          }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "asm-lexer.lpp"
{
            yylval->real = atof(yytext+1);
            return REAL;
          }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "asm-lexer.lpp"
{
            yylval->instruction = ISet.getIstr(yytext);
            return INSTRUCTION;
          }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "asm-lexer.lpp"
return KEYWORD_INT;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "asm-lexer.lpp"
return KEYWORD_LONG;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "asm-lexer.lpp"
return KEYWORD_REAL;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "asm-lexer.lpp"
return KEYWORD_CHAR;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "asm-lexer.lpp"
return KEYWORD_STRING;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "asm-lexer.lpp"
return KEYWORD_LOCAL;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "asm-lexer.lpp"
return KEYWORD_GLOBAL;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "asm-lexer.lpp"
return KEYWORD_FUNCTION;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "asm-lexer.lpp"
return KEYWORD_END;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 86 "asm-lexer.lpp"
yylval->integer = atoi(yytext+1); return CONTENT_CONST;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 87 "asm-lexer.lpp"
yytext[yyleng-1] = '\0'; yylval->label = yytext+1; return DEF_LABEL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 88 "asm-lexer.lpp"
yylval->label = yytext+1; return CONTENT_LABEL;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "asm-lexer.lpp"
yylval->label = yytext+1; return POSITION_LABEL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "asm-lexer.lpp"
{
            createSpecialRegArg(yylval->arg, yylloc, STATE_REGISTER);
            return REGISTER;
          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "asm-lexer.lpp"
{
            createSpecialRegArg(yylval->arg, yylloc, STACK_POINTER);
            return REGISTER;
          }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "asm-lexer.lpp"
{
            createSpecialRegArg(yylval->arg, yylloc, USER_STACK_POINTER);
            return REGISTER;
          }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG, 0, false);
            return REGISTER;
          }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG, OFFSET_REGS,false);
            return REGISTER;
          }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+3, REG_PRE_INCR,
                          0, false);
            return REGISTER;
          }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 116 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+3, REG_PRE_INCR,
                          OFFSET_REGS, false);
            return REGISTER;
          }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 121 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+3, REG_PRE_DECR,
                          0, false);
            return REGISTER;
          }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+3, REG_PRE_DECR,
                          OFFSET_REGS, false);
            return REGISTER;
          }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 131 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG_POST_INCR,
                          0, false);
            return REGISTER;
          }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 136 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG_POST_INCR,
                          OFFSET_REGS, false);
            return REGISTER;
          }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG_POST_DECR,
                          0, false);
            return REGISTER;
          }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 146 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+2, REG_POST_DECR,
                          OFFSET_REGS, false);
            return REGISTER;
          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 152 "asm-lexer.lpp"
{
            createSpecialAddrRegArg(yylval->arg, yylloc, STATE_REGISTER,
                                    (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 157 "asm-lexer.lpp"
{
            createSpecialAddrRegArg(yylval->arg, yylloc, STACK_POINTER,
                                    (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 162 "asm-lexer.lpp"
{
            createSpecialAddrRegArg(yylval->arg, yylloc, USER_STACK_POINTER,
                                    (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 167 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG, 0, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 172 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG, OFFSET_REGS, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 177 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 4 : 3),
                          ADDR_IN_REG_PRE_INCR, 0, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 182 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 4 : 3),
                          ADDR_IN_REG_PRE_INCR, OFFSET_REGS, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 187 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 4 : 3),
                          ADDR_IN_REG_PRE_DECR, 0, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 192 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 4 : 3),
                          ADDR_IN_REG_PRE_DECR, OFFSET_REGS, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 197 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG_POST_INCR, 0, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 202 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG_POST_INCR, OFFSET_REGS, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 207 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG_POST_DECR, 0, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 212 "asm-lexer.lpp"
{
            createRegArg(yylval->arg, yylloc, yytext+((*yytext) == 'r' ? 3 : 2),
                          ADDR_IN_REG_POST_DECR, OFFSET_REGS, (*yytext) == 'r');
            return REGISTER;
          }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 218 "asm-lexer.lpp"
yylval->id = yytext; return ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 220 "asm-lexer.lpp"
BEGIN(COMMENT);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 222 "asm-lexer.lpp"
{
            string_buf_ptr = string_buf;
            BEGIN(STRING_CONTEXT);
          }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 227 "asm-lexer.lpp"
{
            yylloc->first_line++;
            yylloc->first_column = 1;
            yylloc->last_line++;
            yylloc->last_column = 1;
            return END_LINE;
          }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 235 "asm-lexer.lpp"
{
            fprintf( stderr, "Lexing Error, unknown symbol: %s\n", yytext );
            exit(1);
          }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 239 "asm-lexer.lpp"
/* eat up whitespace */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "asm-lexer.lpp"
return COMA;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 242 "asm-lexer.lpp"
{
            fprintf( stderr, "Lexing Error, unknown symbol: %s\n", yytext );
            exit(1);
          }
	YY_BREAK


case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 249 "asm-lexer.lpp"
{
            yylloc->first_line++;
            yylloc->first_column = 1;
            yylloc->last_line++;
            yylloc->last_column = 1;
            return END_LINE;
          }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 256 "asm-lexer.lpp"
BEGIN(INITIAL);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 257 "asm-lexer.lpp"
/* eat up */
	YY_BREAK


case 54:
YY_RULE_SETUP
#line 261 "asm-lexer.lpp"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 262 "asm-lexer.lpp"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 263 "asm-lexer.lpp"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 264 "asm-lexer.lpp"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 265 "asm-lexer.lpp"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 267 "asm-lexer.lpp"
{
            *string_buf_ptr++ = yytext[0];
            *string_buf_ptr++ = yytext[1];
          }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 272 "asm-lexer.lpp"
{
            char *yptr = yytext;
            while ( *yptr )
              *string_buf_ptr++ = *yptr++;
          }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 278 "asm-lexer.lpp"
{
            BEGIN(INITIAL);
            *string_buf_ptr = '\0';
            yylval->string = string_buf;
            return STRING;
          }
	YY_BREAK

case 62:
YY_RULE_SETUP
#line 286 "asm-lexer.lpp"
ECHO;
	YY_BREAK
#line 1429 "asm-lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING_CONTEXT):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 247);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef _UNISTD_H /* assume unistd.h has isatty() for us */
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __THROW /* this is a gnuism */
extern int isatty (int ) __THROW;
#else
extern int isatty (int );
#endif
#ifdef __cplusplus
}
#endif
#endif
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 286 "asm-lexer.lpp"



int getRegNum(const char * str) {
  char * tempStr = strndup(str,1);
  int num = atoi(tempStr) -1;
  free(tempStr);
  return num;
}

void createRegArg(asm_arg *& arg, YYLTYPE *& loc, const char * str,
                  const TypeOfArgument& type, const int& offset, const bool rel)
{
  asm_immediate_arg * tempArg = new asm_immediate_arg(*loc);
  tempArg->relative = rel;
  tempArg->type = type;
  tempArg->content.val = getRegNum(str) + offset;
  arg = tempArg;
}
void createSpecialRegArg(asm_arg *& arg, YYLTYPE *& loc,
                  const enum Registers& reg)
{
  asm_immediate_arg * tempArg = new asm_immediate_arg(*loc);
  tempArg->type = REG;
  tempArg->content.regNum = reg;
  tempArg->relative = false;
  arg = tempArg;
}
void createSpecialAddrRegArg(asm_arg *& arg, YYLTYPE *& loc,
                  const enum Registers& reg, const bool rel)
{
  asm_immediate_arg * tempArg = new asm_immediate_arg(*loc);
  tempArg->type = ADDR_IN_REG;
  tempArg->content.regNum = reg;
  tempArg->relative = rel;
  arg = tempArg;
}
void createConstIntArg(asm_arg *& arg, YYLTYPE *& loc, const int _val) {
  asm_immediate_arg * tempArg = new asm_immediate_arg(*loc);
  tempArg->type = COST;
  tempArg->content.val = _val;
  tempArg->relative = false;
  arg = tempArg;
}
void createConstRealArg(asm_arg *& arg, YYLTYPE *& loc, const float _val) {
  asm_immediate_arg * tempArg = new asm_immediate_arg(*loc);
  tempArg->type = COST;
  tempArg->content.fval = _val;
  tempArg->relative = false;
  arg = tempArg;
}

